export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const RESET_GET_PRODUCTS = 'RESET_GET_PRODUCTS';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const ADD_PRODUCT_COUNT = 'ADD_PRODUCT_COUNT';
export const SUBTRACT_PRODUCT_COUNT = 'SUBTRACT_PRODUCT_COUNT';